const initialState = {
    pieces: {
        WR1: {col: 1, row: 1, color: 'white', captured: false, type: 'rook', pieceImage: 'R'},
        WKn1: {col: 2, row: 1, color: 'white', captured: false, type: 'knight', pieceImage: 'Kn'},
        WB1: {col: 3, row: 1, color: 'white', captured: false, type: 'bishop', pieceImage: 'B'},
        WK: {col: 4, row: 1, color: 'white', captured: false, type: 'king', pieceImage: 'K'},
        WQ: {col: 5, row: 1, color: 'white', captured: false, type: 'queen', pieceImage: 'Q'},
        WB2: {col: 6, row: 1, color: 'white', captured: false, type: 'bishop', pieceImage: 'B'},
        WKn2: {col: 7, row: 1, color: 'white', captured: false, type: 'knight', pieceImage: 'Kn'},
        WR2: {col: 8, row: 1, color: 'white', captured: false, type: 'rook', pieceImage: 'R'},
        WP1: {col: 1, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        WP2: {col: 2, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        WP3: {col: 3, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        WP4: {col: 4, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        WP5: {col: 5, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        WP6: {col: 6, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        WP7: {col: 7, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        WP8: {col: 8, row: 2, color: 'white', captured: false, type: 'pawn', pieceImage: 'P'},
        BR1: {col: 1, row: 8, color: 'black', captured: false, type: 'rook', pieceImage: 'R'},
        BKn1: {col: 2, row: 8, color: 'black', captured: false, type: 'knight', pieceImage: 'Kn'},
        BB1: {col: 3, row: 8, color: 'black', captured: false, type: 'bishop', pieceImage: 'B'},
        BK: {col: 4, row: 8, color: 'black', captured: false, type: 'king', pieceImage: 'K'},
        BQ: {col: 5, row: 8, color: 'black', captured: false, type: 'queen', pieceImage: 'Q'},
        BB2: {col: 6, row: 8, color: 'black', captured: false, type: 'bishop', pieceImage: 'B'},
        BKn2: {col: 7, row: 8, color: 'black', captured: false, type: 'knight', pieceImage: 'Kn'},
        BR2: {col: 8, row: 8, color: 'black', captured: false, type: 'rook', pieceImage: 'R'},
        BP1: {col: 1, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
        BP2: {col: 2, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
        BP3: {col: 3, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
        BP4: {col: 4, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
        BP5: {col: 5, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
        BP6: {col: 6, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
        BP7: {col: 7, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
        BP8: {col: 8, row: 7, color: 'black', captured: false, type: 'pawn', pieceImage: 'P'},
    },
    boardTiles: {
        S1: {col:1, row:1, highlight:false, occupied: false},
        S2: {col:2, row:1, highlight:false, occupied: false},
        S3: {col:3, row:1, highlight:false, occupied: false},
        S4: {col:4, row:1, highlight:false, occupied: false},
        S5: {col:5, row:1, highlight:false, occupied: false},
        S6: {col:6, row:1, highlight:false, occupied: false},
        S7: {col:7, row:1, highlight:false, occupied: false},
        S8: {col:8, row:1, highlight:false, occupied: false},
        S9: {col:1, row:2, highlight:false, occupied: false},
        S10: {col:2, row:2, highlight:false, occupied: false},
        S11: {col:3, row:2, highlight:false, occupied: false},
        S12: {col:4, row:2, highlight:false, occupied: false},
        S13: {col:5, row:2, highlight:false, occupied: false},
        S14: {col:6, row:2, highlight:false, occupied: false},
        S15: {col:7, row:2, highlight:false, occupied: false},
        S16: {col:8, row:2, highlight:false, occupied: false},
        S17: {col:1, row:3, highlight:false, occupied: false},
        S18: {col:2, row:3, highlight:false, occupied: false},
        S19: {col:3, row:3, highlight:false, occupied: false},
        S20: {col:4, row:3, highlight:false, occupied: false},
        S21: {col:5, row:3, highlight:false, occupied: false},
        S22: {col:6, row:3, highlight:false, occupied: false},
        S23: {col:7, row:3, highlight:false, occupied: false},
        S24: {col:8, row:3, highlight:false, occupied: false},
        S25: {col:1, row:4, highlight:false, occupied: false},
        S26: {col:2, row:4, highlight:false, occupied: false},
        S27: {col:3, row:4, highlight:false, occupied: false},
        S28: {col:4, row:4, highlight:false, occupied: false},
        S29: {col:5, row:4, highlight:false, occupied: false},
        S30: {col:6, row:4, highlight:false, occupied: false},
        S31: {col:7, row:4, highlight:false, occupied: false},
        S32: {col:8, row:4, highlight:false, occupied: false},
        S33: {col:1, row:1, highlight:false, occupied: false},
        S34: {col:2, row:1, highlight:false, occupied: false},
        S35: {col:3, row:1, highlight:false, occupied: false},
        S36: {col:4, row:1, highlight:false, occupied: false},
        S37: {col:5, row:1, highlight:false, occupied: false},
        S38: {col:6, row:1, highlight:false, occupied: false},
        S39: {col:7, row:1, highlight:false, occupied: false},
        S40: {col:8, row:1, highlight:false, occupied: false},
        S41: {col:1, row:2, highlight:false, occupied: false},
        S42: {col:2, row:2, highlight:false, occupied: false},
        S43: {col:3, row:2, highlight:false, occupied: false},
        S44: {col:4, row:2, highlight:false, occupied: false},
        S45: {col:5, row:2, highlight:false, occupied: false},
        S46: {col:6, row:2, highlight:false, occupied: false},
        S47: {col:7, row:2, highlight:false, occupied: false},
        S48: {col:8, row:2, highlight:false, occupied: false},
        S49: {col:1, row:3, highlight:false, occupied: false},
        S50: {col:2, row:3, highlight:false, occupied: false},
        S51: {col:3, row:3, highlight:false, occupied: false},
        S52: {col:4, row:3, highlight:false, occupied: false},
        S53: {col:5, row:3, highlight:false, occupied: false},
        S54: {col:6, row:3, highlight:false, occupied: false},
        S55: {col:7, row:3, highlight:false, occupied: false},
        S56: {col:8, row:3, highlight:false, occupied: false},
        S57: {col:1, row:4, highlight:false, occupied: false},
        S58: {col:2, row:4, highlight:false, occupied: false},
        S59: {col:3, row:4, highlight:false, occupied: false},
        S60: {col:4, row:4, highlight:false, occupied: false},
        S61: {col:5, row:4, highlight:false, occupied: false},
        S62: {col:6, row:4, highlight:false, occupied: false},
        S63: {col:7, row:4, highlight:false, occupied: false},
        S64: {col:8, row:4, highlight:false, occupied: false}
    }
}

export default function chessSetReducer(state = initialState, action) {
    switch (action.type) {
      default:
        return state;
    }
}